### ISSUE TITLE
Cursors

### ISSUE THREAD

**Issue by kinseyost** [christianalfoni/cerebral-baobab#4]
@christianalfoni Is there a reason you did not enable cursors for cerebral-baobab?

**Comment by christianalfoni** [comment]
Hi @kinseyost ,

Jup, because you do not need them.

When Baobab was first released it was not immutable. That means you would have to rerender your whole application on every change to the tree. This is what cursors helped us with. Only render parts of the application related to a specific path in the tree.

With immutability we do not need this. We just have one listener on the tree itself, using shallow checking to decide what is necessary to render. That way we prevent having lots of listeners all over the place, its more predictable and shallow checks is blazingly fast :)

**Comment by christianalfoni** [comment]
Just closing it, please let me know if you have more questions about this
